# Generated by Django 4.2.7 on 2026-07-17 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('welcome', 'Welcome Email'), ('otp_verification', 'OTP Verification'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('expiry_warning', 'Expiry Warning'), ('bulk_announcement', 'Bulk Announcement'), ('password_reset', 'Password Reset')], max_length=30)),
                ('subject', models.CharField(max_length=200)),
                ('html_content', models.TextField()),
                ('text_content', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_variables', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'email_templates',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BulkNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('target_audience', models.CharField(choices=[('all_users', 'All Users'), ('admin_users', 'Admin Users'), ('regular_users', 'Regular Users'), ('house_plan_users', 'House Plan Users'), ('individual_plan_users', 'Individual Plan Users'), ('business_plan_users', 'Business Plan Users'), ('verified_users', 'Verified Users'), ('unverified_users', 'Unverified Users')], max_length=30)),
                ('notification_type', models.CharField(choices=[('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('payment_reminder', 'Payment Reminder'), ('codes_assigned', 'Access Codes Assigned'), ('expiry_warning', 'Expiry Warning'), ('low_stock', 'Low Stock Alert'), ('system_announcement', 'System Announcement'), ('account_update', 'Account Update'), ('general', 'General')], default='system_announcement', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('total_recipients', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('action_url', models.URLField(blank=True)),
                ('action_text', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bulk_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('payment_reminder', 'Payment Reminder'), ('codes_assigned', 'Access Codes Assigned'), ('expiry_warning', 'Expiry Warning'), ('low_stock', 'Low Stock Alert'), ('system_announcement', 'System Announcement'), ('account_update', 'Account Update'), ('general', 'General')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_url', models.URLField(blank=True)),
                ('action_text', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='idx_notif_user_read'), models.Index(fields=['user', 'notification_type'], name='idx_notif_user_type'), models.Index(fields=['created_at'], name='idx_notif_created')],
            },
        ),
    ]
