# Generated by Django 4.2.7 on 2026-07-17 13:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('house', 'House'), ('individual', 'Individual'), ('business', 'Business')], max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validity', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('validity_days', models.IntegerField(help_text='Number of days the plan is valid')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plans',
                'ordering': ['plan_type', 'cost'],
                'indexes': [models.Index(fields=['plan_type', 'is_active'], name='idx_plan_type_active'), models.Index(fields=['is_active'], name='idx_plan_active')],
            },
        ),
    ]
